sudo: required
services:
- docker


before_install:
- docker build -t dineshsonachalam/hacker:1.0.0 .
script:
    #log in to docker CLI
  - echo "123456" | docker login -u "1" --password-stdin
    #take built images and push to Docker hub
  - docker push dineshsonachalam/hacker:1.0.0